repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint (local)
        entry: npx eslint
        language: system
        files: \.(ts|tsx|js|jsx)$
        args: ['--ext', '.ts,.tsx,.js,.jsx', '--max-warnings=0']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: ['--write']
