name: unit-test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run Vitest
        run: npx vitest run
